[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    tzapu/WiFiManager @ ^2.0.16-rc.2
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0

[env:wokwi]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
    -D WOKWI_SIMULATION
lib_deps =
    ${env:esp32dev.lib_deps}